import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import CreateEventDrawer from "@/components/create-events";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({subsets:["latin"]})
export default function RootLayout({ children }) {
  return (
    <ClerkProvider>

    <html lang="en">
      <body className={inter.className}>
        <Header/>
        {/* Header */}
        <main className="min-h-screen bg-gradient-to-b from-blue-40 to-white">
          {children} 
          </main>
          <footer className= "bg-gray-100 py-10 flex justify-center align-middle">
            <div >
              <p className="font-semibold text-black-500">
                Made with ❤ by All In One
              </p>
            </div>
          </footer>
          <CreateEventDrawer/>
        {/* footer */}
      </body>
    </html>
    </ClerkProvider>
  );
}
